// frontend/src/components/ModpackSidebar.tsx
import {Plus, Settings} from 'lucide-react';
import {LogOut} from 'lucide-react';
import {ModpackResponse} from '../types/api';

interface ModpackSidebarProps {
    modpacks: ModpackResponse[];
    selectedModpack: number | null;
    onSelectModpack: (id: number) => void;
    onNewModpack: () => void;
    showForm: boolean;
    onShowSettings: () => void;
    showSettings: boolean;
    onLogout: () => void;
}

export default function ModpackSidebar(
    {
        modpacks,
        selectedModpack,
        onSelectModpack,
        onNewModpack,
        showForm,
        onShowSettings,
        showSettings,
        onLogout
    }: ModpackSidebarProps) {
    return (
        <div className="w-80 h-screen sticky top-0 bg-gray-800 border-r border-gray-700 flex flex-col">
            <div className="p-6 border-b border-gray-700">
                <h1 className="text-2xl font-bold text-white mb-4">Modpack Manager</h1>
                <button
                    onClick={onNewModpack}
                    className={`w-full flex items-center gap-2 px-4 py-3 rounded-md text-white font-medium transition-all duration-200 ${
                        showForm
                            ? 'bg-green-600 hover:bg-green-700'
                            : 'bg-green-500 hover:bg-green-600'
                    }`}
                >
                    <Plus size={20}/>
                    New Modpack
                </button>
            </div>

            <div className="flex-1 overflow-y-auto">
                <div className="p-4">
                    <h2 className="text-gray-400 text-sm font-medium uppercase tracking-wide mb-3">
                        Existing Modpacks
                    </h2>
                    {modpacks.length === 0 ? (
                        <p className="text-gray-500 text-sm italic">No modpacks yet</p>
                    ) : (
                        <div className="space-y-2">
                            {modpacks.map((modpack) => (
                                <button
                                    key={modpack.id}
                                    onClick={() => onSelectModpack(modpack.id)}
                                    className={`w-full text-left p-3 rounded-md transition-all duration-200 border ${
                                        selectedModpack === modpack.id
                                            ? 'bg-green-900/30 border-green-500 text-green-400'
                                            : 'bg-gray-700/50 border-gray-600 text-gray-300 hover:bg-gray-700 hover:border-gray-500'
                                    }`}
                                >
                                    <div className="font-medium">{modpack.name}</div>
                                    <div className="text-sm text-gray-400">{modpack.minecraft_version}</div>
                                </button>
                            ))}
                        </div>
                    )}
                </div>
            </div>

            <div className="p-4 border-t border-gray-700 bg-gray-800">
                <div className="space-y-2">
                    <button
                        onClick={onShowSettings}
                        className={`w-full flex items-center gap-2 px-4 py-3 rounded-md text-white font-medium transition-all duration-200 ${
                            showSettings
                                ? 'bg-blue-600 hover:bg-blue-700'
                                : 'bg-gray-700 hover:bg-gray-600'
                        }`}
                    >
                        <Settings size={20}/>
                        Settings
                    </button>
                    <button
                        onClick={onLogout}
                        className="w-full flex items-center gap-2 px-4 py-3 rounded-md text-white font-medium transition-all duration-200 bg-red-600 hover:bg-red-700"
                    >
                        <LogOut size={20}/>
                        Logout
                    </button>
                </div>
            </div>
        </div>
    );
}

// frontend/src/components/ModpackSidebar.vue
<script setup lang="ts">
import type { ModpackResponse } from '@/types/api';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

const props = defineProps<{
  modpacks: ModpackResponse[];
  selectedModpack: number | null;
  showForm: boolean;
  showSettings: boolean;
  building: boolean;
}>();

const emit = defineEmits<{
  (event: 'select', id: number): void;
  (event: 'new'): void;
  (event: 'show-settings'): void;
  (event: 'logout'): void;
  (event: 'build'): void;
}>();
</script>

<template>
  <aside class="min-h-screen w-72 p-4">
    <Card class="h-full">
      <CardContent class="flex h-full flex-col gap-4 p-4">
        <div class="space-y-3">
          <h1>Modpack Manager</h1>
          <Button class="w-full" size="sm" @click="emit('new')">
            New Modpack
          </Button>
          <Button class="w-full" size="sm" :disabled="props.building" @click="emit('build')">
            {{ props.building ? 'Building…' : 'Build' }}
          </Button>
        </div>

        <div class="flex-1 space-y-3 overflow-y-auto">
          <p>Existing Modpacks</p>
          <p v-if="props.modpacks.length === 0">No modpacks yet</p>
          <div v-else class="space-y-2">
            <Button v-for="modpack in props.modpacks" :key="modpack.id" class="w-full justify-between"
              @click="emit('select', modpack.id)">
              <span>{{ modpack.name }}</span>
              <span>{{ modpack.minecraft_version }}</span>
            </Button>
          </div>
        </div>

        <div class="space-y-2">
          <Button class="w-full" @click="emit('show-settings')">
            Settings
          </Button>
          <Button class="w-full" @click="emit('logout')">
            Logout
          </Button>
        </div>
      </CardContent>
    </Card>
  </aside>
</template>
