// frontend/src/components/SettingsForm.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { Save } from 'lucide-vue-next';
import { apiService } from '@/services/api';
import type { SettingResponse } from '@/types/api';
import { SettingType } from '@/types/api';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Alert, AlertDescription } from '@/components/ui/alert';

const emit = defineEmits<{
  (event: 'saved', payload: SettingResponse[]): void;
}>();

const defaultSettings: SettingResponse[] = [
  { key: 'download_server_base', value: '', type: SettingType.STRING },
  { key: 'resources_url_base', value: '', type: SettingType.STRING },
  { key: 'replace_download_urls', value: false, type: SettingType.BOOLEAN },
  { key: 'version_manifest_url', value: '', type: SettingType.STRING },
];

const displaySettings = ref<SettingResponse[]>([]);
const originalSettings = ref<SettingResponse[]>([]);
const loading = ref(true);
const saving = ref(false);
const error = ref<string | null>(null);

const mergedDefaultSettings = () =>
  defaultSettings.map((setting) => {
    const serverValue = originalSettings.value.find((s) => s.key === setting.key);
    return serverValue ?? setting;
  });

const hasChanges = computed(() =>
  displaySettings.value.some((setting) => {
    const original = originalSettings.value.find((s) => s.key === setting.key);
    const fallback = defaultSettings.find((s) => s.key === setting.key);
    const originalValue = original?.value ?? fallback?.value;
    return setting.value !== originalValue;
  }),
);

const getSetting = (key: string) => displaySettings.value.find((s) => s.key === key);

const loadSettings = async () => {
  try {
    loading.value = true;
    error.value = null;
    const data = await apiService.getSettings();
    originalSettings.value = data;
    displaySettings.value = mergedDefaultSettings().map((setting) => {
      const serverSetting = data.find((s) => s.key === setting.key);
      return serverSetting ?? setting;
    });
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load settings';
    displaySettings.value = mergedDefaultSettings();
  } finally {
    loading.value = false;
  }
};

const handleInputChange = (key: string, value: string | boolean) => {
  displaySettings.value = displaySettings.value.map((setting) =>
    setting.key === key ? { ...setting, value } : setting,
  );
};

const handleSave = async () => {
  try {
    saving.value = true;
    error.value = null;

    const changedSettings = displaySettings.value.filter((setting) => {
      const original = originalSettings.value.find((s) => s.key === setting.key);
      const fallback = defaultSettings.find((s) => s.key === setting.key);
      const originalValue = original?.value ?? fallback?.value;
      return setting.value !== originalValue;
    });

    await apiService.updateSettings(changedSettings);
    originalSettings.value = displaySettings.value.map((setting) => ({ ...setting }));
    emit('saved', displaySettings.value);
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to save settings';
  } finally {
    saving.value = false;
  }
};

onMounted(() => {
  loadSettings().catch((err) => console.error(err));
});
</script>

<template>
  <div class="p-4">
    <Card>
      <CardHeader>
        <CardTitle>Application Settings</CardTitle>
        <CardDescription>Update launcher URLs and deployment toggles.</CardDescription>
      </CardHeader>
      <CardContent>
        <div v-if="loading" class="text-sm">Loading settings...</div>
        <template v-else>
          <Alert v-if="error" variant="destructive" class="mb-4">
            <AlertDescription class="flex items-center justify-between gap-2">
              <span>{{ error }}</span>
              <Button size="sm" @click="loadSettings">
                Retry
              </Button>
            </AlertDescription>
          </Alert>
          <div v-if="displaySettings.length" class="space-y-6">
            <div v-if="getSetting('download_server_base')" class="space-y-2">
              <Label for="download_server_base">Download Server Base URL</Label>
              <Input id="download_server_base" :model-value="getSetting('download_server_base')?.value as string | ''"
                placeholder="https://your-server.com"
                @update:modelValue="(value) => handleInputChange('download_server_base', value?.toString() ?? '')" />
              <p class="text-sm">
                Base URL used when generating download links.
              </p>
            </div>
            <div v-if="getSetting('resources_url_base')" class="space-y-2">
              <Label for="resources_url_base">Resources URL Base</Label>
              <Input id="resources_url_base" :model-value="getSetting('resources_url_base')?.value as string | ''"
                placeholder="https://your-server.com/assets/objects"
                @update:modelValue="(value) => handleInputChange('resources_url_base', value?.toString() ?? '')" />
              <p class="text-sm">
                Leave blank to fall back to Mojang asset endpoints.
              </p>
            </div>
            <div v-if="getSetting('replace_download_urls')" class="space-y-2">
              <Label>Replace Download URLs</Label>
              <Select :model-value="getSetting('replace_download_urls')?.value?.toString() ?? 'false'"
                @update:modelValue="(value) => handleInputChange('replace_download_urls', value === 'true')">
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="false">false</SelectItem>
                  <SelectItem value="true">true</SelectItem>
                </SelectContent>
              </Select>
              <p class="text-sm">
                Toggle to redirect every download through your infrastructure.
              </p>
            </div>
            <div v-if="getSetting('version_manifest_url')" class="space-y-2">
              <Label for="version_manifest_url">Version Manifest URL</Label>
              <Input id="version_manifest_url" :model-value="getSetting('version_manifest_url')?.value as string | ''"
                placeholder="https://your-server.com/version_manifest.json"
                @update:modelValue="(value) => handleInputChange('version_manifest_url', value?.toString() ?? '')" />
              <p class="text-sm">
                Merge remote manifest entries with locally defined versions.
              </p>
            </div>
            <div>
              <Button class="gap-2" :disabled="!hasChanges || saving" @click="handleSave">
                <Save class="h-4 w-4" />
                {{ saving ? 'Saving...' : 'Save Settings' }}
              </Button>
              <p v-if="hasChanges" class="mt-2 text-sm">
                Changes are local until you save.
              </p>
            </div>
          </div>
        </template>
      </CardContent>
    </Card>
  </div>
</template>

// frontend/src/components/SettingsForm.tsx
import {useState, useEffect, useCallback, useRef} from 'react';
import {Save} from 'lucide-react';
import {apiService} from '../services/api';
import {SettingResponse, SettingType} from '../types/api';


interface SettingsFormProps {
    onSave: (settings: SettingResponse[]) => void;
}

export default function SettingsForm({onSave}: SettingsFormProps) {
    const [_, setSettings] = useState<SettingResponse[]>([]);
    const [originalSettings, setOriginalSettings] = useState<SettingResponse[]>([]);
    const [displaySettings, setDisplaySettings] = useState<SettingResponse[]>([]);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [hasChanges, setHasChanges] = useState(false);
    const fetchingRef = useRef(false);


    // Default settings that should always be displayed
    const defaultSettings: SettingResponse[] = [
        {key: 'download_server_base', value: '', type: SettingType.STRING},
        {key: 'resources_url_base', value: '', type: SettingType.STRING},
        {key: 'replace_download_urls', value: false, type: SettingType.BOOLEAN},
        {key: 'version_manifest_url', value: '', type: SettingType.STRING},
    ];

    useEffect(() => {
        if (fetchingRef.current) return;
        fetchingRef.current = true;

        loadSettings();
    }, []);

    const loadSettings = async () => {
        try {
            setLoading(true);
            setError(null);
            const data = await apiService.getSettings();
            setSettings(data);
            setOriginalSettings(data);

            // Merge server settings with default settings
            const mergedSettings = defaultSettings.map(defaultSetting => {
                const serverSetting = data.find(s => s.key === defaultSetting.key);
                return serverSetting || defaultSetting;
            });
            setDisplaySettings(mergedSettings);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Failed to load settings');
            // If server fails, show default settings
            setDisplaySettings(defaultSettings);
        } finally {
            setLoading(false);
        }
    };

    const checkForChanges = useCallback(() => {
        const changed = displaySettings.some((setting) => {
            const original = originalSettings.find(s => s.key === setting.key);
            const defaultSetting = defaultSettings.find(s => s.key === setting.key);
            const originalValue = original?.value ?? defaultSetting?.value;
            return setting.value !== originalValue;
        });
        setHasChanges(changed);
    }, [displaySettings, originalSettings]);

    useEffect(() => {
        checkForChanges();
    }, [checkForChanges]);

    const handleInputChange = (key: string, value: string | boolean) => {
        setDisplaySettings(prev => prev.map(setting =>
            setting.key === key ? {...setting, value} : setting
        ));
    };

    const handleSave = async () => {
        try {
            setSaving(true);
            setError(null);

            // Only send changed settings to server
            const changedSettings = displaySettings.filter((setting) => {
                const original = originalSettings.find(s => s.key === setting.key);
                const defaultSetting = defaultSettings.find(s => s.key === setting.key);
                const originalValue = original?.value ?? defaultSetting?.value;
                return setting.value !== originalValue;
            });

            await apiService.updateSettings(changedSettings);

            // Update original settings with current display settings
            const newOriginalSettings = [...originalSettings];
            displaySettings.forEach(displaySetting => {
                const existingIndex = newOriginalSettings.findIndex(s => s.key === displaySetting.key);
                if (existingIndex >= 0) {
                    newOriginalSettings[existingIndex] = displaySetting;
                } else {
                    newOriginalSettings.push(displaySetting);
                }
            });
            setOriginalSettings(newOriginalSettings);
            setHasChanges(false);
            onSave(displaySettings);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Failed to save settings');
        } finally {
            setSaving(false);
        }
    };

    const getSetting = (key: string) => {
        return displaySettings.find(s => s.key === key);
    };

    if (loading) {
        return (
            <div className="max-w-2xl mx-auto">
                <div className="bg-gray-800 rounded-lg border border-gray-700 p-8">
                    <div className="text-center text-white">Loading settings...</div>
                </div>
            </div>
        );
    }

    if (error && !displaySettings.length) {
        return (
            <div className="max-w-2xl mx-auto">
                <div className="bg-gray-800 rounded-lg border border-gray-700 p-8">
                    <div className="text-center">
                        <div className="text-red-400 mb-4">Error: {error}</div>
                        <button
                            onClick={loadSettings}
                            className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
                        >
                            Retry
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-2xl mx-auto">
            <div className="bg-gray-800 rounded-lg border border-gray-700 p-8">
                <h2 className="text-2xl font-bold text-white mb-6">Application Settings</h2>

                {error && (
                    <div className="mb-4 p-3 bg-red-900/20 border border-red-500 rounded-md">
                        <p className="text-red-400 text-sm">{error}</p>
                    </div>
                )}

                <div className="space-y-6">
                    {getSetting('download_server_base') && (
                        <div>
                            <label htmlFor="download_server_base"
                                   className="block text-sm font-medium text-gray-300 mb-2">
                                Download Server Base URL
                            </label>
                            <input
                                id="download_server_base"
                                type="text"
                                value={getSetting('download_server_base')?.value as string || ''}
                                onChange={(e) => handleInputChange('download_server_base', e.target.value)}
                                className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-md text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-200"
                                placeholder="https://your-server.com"
                            />
                            <p className="mt-1 text-sm text-gray-500">The base URL where the instance will be
                                deployed</p>
                        </div>
                    )}

                    {getSetting('resources_url_base') && (
                        <div>
                            <label htmlFor="resources_url_base"
                                   className="block text-sm font-medium text-gray-300 mb-2">
                                Resources URL Base
                            </label>
                            <input
                                id="resources_url_base"
                                type="text"
                                value={getSetting('resources_url_base')?.value as string || ''}
                                onChange={(e) => handleInputChange('resources_url_base', e.target.value)}
                                className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-md text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-200"
                                placeholder="https://your-server.com/assets/objects"
                            />
                            <p className="mt-1 text-sm text-gray-500">
                                The base URL for assets. Should be equal to &lt;download_server_base&gt;/assets/objects
                                if the generated folder structure is not changed after upload. If omitted, the launcher
                                will download assets from Mojang servers.
                            </p>
                        </div>
                    )}

                    {getSetting('replace_download_urls') && (
                        <div>
                            <label htmlFor="replace_download_urls"
                                   className="block text-sm font-medium text-gray-300 mb-2">
                                Replace Download URLs
                            </label>
                            <select
                                id="replace_download_urls"
                                value={getSetting('replace_download_urls')?.value?.toString() || 'false'}
                                onChange={(e) => handleInputChange('replace_download_urls', e.target.value === 'true')}
                                className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-200"
                            >
                                <option value="false">false</option>
                                <option value="true">true</option>
                            </select>
                            <div className="mt-1 text-sm text-gray-500">
                                <p className="mb-2">
                                    <strong>If true:</strong> All instance files will be downloaded from your server.
                                </p>
                                <p>
                                    <strong>If false:</strong> Original download URLs will be kept when possible.
                                    Assets, libraries, modloaders and the Minecraft jar will be downloaded from their
                                    original locations and only metadata, files specified in include, and (Neo)Forge
                                    patched jars will be downloaded from your server.
                                </p>
                            </div>
                        </div>
                    )}

                    {getSetting('version_manifest_url') && (
                        <div>
                            <label htmlFor="version_manifest_url"
                                   className="block text-sm font-medium text-gray-300 mb-2">
                                Version Manifest URL
                            </label>
                            <input
                                id="version_manifest_url"
                                type="text"
                                value={getSetting('version_manifest_url')?.value as string || ''}
                                onChange={(e) => handleInputChange('version_manifest_url', e.target.value)}
                                className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-md text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all duration-200"
                                placeholder="https://your-server.com/version_manifest.json"
                            />
                            <div className="mt-1 text-sm text-gray-500">
                                <p className="mb-2">
                                    The URL from which to fetch a remote version manifest. If specified, the instance
                                    builder will fetch the existing manifest from this URL and merge the local versions
                                    with it, preserving any versions that exist in the remote manifest but not in the
                                    local specification.
                                </p>
                                <p>
                                    Set this to &lt;download_server_base&gt;/version_manifest.json if you want to manage
                                    different instances from different devices (for example, when you have multiple
                                    server admins responsible for different servers).
                                </p>
                            </div>
                        </div>
                    )}

                    <div className="pt-4">
                        <button
                            onClick={handleSave}
                            disabled={!hasChanges || saving}
                            className={`flex items-center gap-2 px-6 py-3 rounded-md font-medium transition-all duration-200 ${
                                hasChanges && !saving
                                    ? 'bg-green-500 hover:bg-green-600 text-white cursor-pointer'
                                    : 'bg-gray-600 text-gray-400 cursor-not-allowed'
                            }`}
                        >
                            <Save size={20}/>
                            {saving ? 'Saving...' : 'Save Settings'}
                        </button>
                        {hasChanges && (
                            <p className="mt-2 text-sm text-yellow-400">You have unsaved changes</p>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
