// frontend/src/App.tsx
import {useState, useEffect} from 'react';
import LoginForm from './components/LoginForm';
import ModpackSidebar from './components/ModpackSidebar';
import ModpackForm from './components/ModpackForm';
import ModpackDetails from './components/ModpackDetails';
import SettingsForm from './components/SettingsForm';
import {useAuth} from './hooks/useAuth';
import {useWebSocket} from './hooks/useWebSocket';
import {useNotification} from './hooks/useNotification';
import Notification from './components/Notification';
import {apiService} from './services/api';
import {ModpackResponse, ModpackBase} from './types/api';
import {useRef} from 'react';


function App() {
    const { isAuthenticated, loading: authLoading, error: authError, login, logout } = useAuth();
    const { notification, hideNotification, showSuccess, showError } = useNotification();
    const [modpacks, setModpacks] = useState<ModpackResponse[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const [selectedModpack, setSelectedModpack] = useState<number | null>(null);
    const [showForm, setShowForm] = useState(false);
    const [showSettings, setShowSettings] = useState(false);
    const [_, setBuilding] = useState(false);
    const fetchingRef = useRef(false);

    // WebSocket connection for real-time updates
    useWebSocket({
        onModpackChange: (data) => {
            console.log('Modpack change received:', data);
            // Reload modpacks when changes are received
            loadModpacks();
        },
        onNotification: (data) => {
            console.log('Notification received:', data);
            // Handle notifications (could show toast, etc.)
        },
        enabled: isAuthenticated
    });

    // Set up unauthorized handler
    useEffect(() => {
        apiService.setUnauthorizedHandler(() => {
            logout();
        });
    }, [logout]);

    useEffect(() => {
        if (!isAuthenticated) return;

        if (fetchingRef.current) return;
        fetchingRef.current = true;

        loadModpacks();
    }, [isAuthenticated]);

    const loadModpacks = async () => {
        fetchingRef.current = false; // Reset flag to allow reloading
        try {
            setLoading(true);
            setError(null);
            const data = await apiService.getModpacks();
            setModpacks(data);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Failed to load modpacks');
        } finally {
            setLoading(false);
            fetchingRef.current = false;
        }
    };

    const handleNewModpack = () => {
        setShowForm(true);
        setSelectedModpack(null);
        setShowSettings(false);
    };

    const handleSelectModpack = (id: number) => {
        setSelectedModpack(id);
        setShowForm(false);
        setShowSettings(false);
    };

    const handleShowSettings = () => {
        setShowSettings(true);
        setShowForm(false);
        setSelectedModpack(null);
    };

    const handleModpackUpdate = (id: number, updatedData: Partial<ModpackResponse>) => {
        setModpacks(prev => prev.map(modpack =>
            modpack.id === id ? {...modpack, ...updatedData} : modpack
        ));
    };

    const handleModpackDelete = async (id: number) => {
        try {
            await apiService.deleteModpack(id);
            // Reload modpacks and clear selection
            setModpacks(prev => prev.filter(modpack => modpack.id !== id));
            if (selectedModpack === id) {
                setSelectedModpack(null);
            }
        } catch (err) {
            console.error('Failed to delete modpack:', err);
            // Reload from server in case of error
            await loadModpacks();
        }
    };

    const handleFormSubmit = async (_: ModpackBase) => {
        // The form handles creation and file upload internally
        // Just reload modpacks and update UI state
        await loadModpacks();
        setShowForm(false);
        setShowSettings(false);
    };

    const handleSettingsSave = (settings: any) => {
        console.log('Settings saved:', settings);
    };

    const handleBuild = async () => {
        try {
            setBuilding(true);
            await apiService.buildModpacks();
            showSuccess('Build started successfully!');
        } catch (err) {
            const errorMessage = err instanceof Error ? err.message : 'Build failed';
            showError(`Build failed: ${errorMessage}`);
        } finally {
            setBuilding(false);
        }
    };

    // Show login form if not authenticated
    if (!isAuthenticated) {
        return (
            <LoginForm
                onLogin={login}
                loading={authLoading}
                error={authError}
            />
        );
    }

    const selectedModpackData = modpacks.find(m => m.id === selectedModpack);

    if (loading) {
        return (
            <div className="min-h-screen bg-gray-900 flex items-center justify-center">
                <div className="text-white text-xl">Loading...</div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="min-h-screen bg-gray-900 flex items-center justify-center">
                <div className="text-center">
                    <div className="text-red-400 text-xl mb-4">Error: {error}</div>
                    <button
                        onClick={loadModpacks}
                        className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
                    >
                        Retry
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-900 flex" style={{margin: '0 auto'}}>
            <Notification
                type={notification.type}
                message={notification.message}
                isVisible={notification.isVisible}
                onClose={hideNotification}
            />
            <ModpackSidebar
                modpacks={modpacks}
                selectedModpack={selectedModpack}
                onSelectModpack={handleSelectModpack}
                onNewModpack={handleNewModpack}
                showForm={showForm}
                onShowSettings={handleShowSettings}
                showSettings={showSettings}
                onLogout={logout}
                onBuild={handleBuild}
            />

            <div className="flex-1 p-8">
                {showForm ? (
                    <ModpackForm onSubmit={handleFormSubmit}/>
                ) : showSettings ? (
                    <SettingsForm onSave={handleSettingsSave}/>
                ) : selectedModpackData ? (
                    <ModpackDetails
                        key={selectedModpack || 'none'}
                        modpack={selectedModpackData}
                        onUpdate={handleModpackUpdate}
                        onDelete={handleModpackDelete}
                    />
                ) : (
                    <div className="flex items-center justify-center h-full">
                        <div className="text-center">
                            <h2 className="text-2xl font-bold text-gray-400 mb-4">
                                Welcome to Modpack Manager
                            </h2>
                            <p className="text-gray-500 mb-8">
                                Select a modpack from the sidebar or create a new one to get started.
                            </p>
                            <button
                                onClick={handleNewModpack}
                                className="bg-green-500 hover:bg-green-600 text-white font-bold py-3 px-6 rounded-md transition-colors duration-200"
                            >
                                Create Your First Modpack
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}

export default App;

// frontend/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import LoginForm from '@/components/LoginForm.vue';
import ModpackSidebar from '@/components/ModpackSidebar.vue';
import ModpackForm from '@/components/ModpackForm.vue';
import ModpackDetails from '@/components/ModpackDetails.vue';
import SettingsForm from '@/components/SettingsForm.vue';
import NotificationToast from '@/components/NotificationToast.vue';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useAuth } from '@/composables/useAuth';
import { useNotification } from '@/composables/useNotification';
import { useWebSocket } from '@/composables/useWebSocket';
import { apiService } from '@/services/api';
import type { ModpackBase, ModpackResponse, SettingResponse } from '@/types/api';

const { isAuthenticated, loading: authLoading, error: authError, login, logout } = useAuth();
const { notification, hideNotification, showSuccess, showError, showInfo } = useNotification();

const modpacks = ref<ModpackResponse[]>([]);
const loading = ref(true);
const error = ref<string | null>(null);
const selectedModpack = ref<number | null>(null);
const showForm = ref(false);
const showSettings = ref(false);
const building = ref(false);
const fetching = ref(false);

const selectedModpackData = computed(() =>
  modpacks.value.find((m) => m.id === selectedModpack.value) ?? null,
);

const loadModpacks = async () => {
  if (fetching.value) return;
  fetching.value = true;
  try {
    loading.value = true;
    error.value = null;
    modpacks.value = await apiService.getModpacks();
    if (selectedModpack.value) {
      const exists = modpacks.value.some((m) => m.id === selectedModpack.value);
      if (!exists) {
        selectedModpack.value = null;
      }
    }
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load modpacks';
  } finally {
    loading.value = false;
    fetching.value = false;
  }
};

onMounted(() => {
  apiService.setUnauthorizedHandler(() => {
    logout();
  });
});

watch(
  isAuthenticated,
  (authed) => {
    if (authed) {
      loadModpacks().catch((err) => console.error(err));
    } else {
      modpacks.value = [];
      selectedModpack.value = null;
      showForm.value = false;
      showSettings.value = false;
      loading.value = false;
      error.value = null;
    }
  },
  { immediate: true },
);

useWebSocket({
  enabled: isAuthenticated,
  onModpackChange: () => {
    loadModpacks().catch((err) => console.error(err));
  },
  onNotification: (data) => {
    if (data && typeof data === 'object' && 'message' in data) {
      showInfo((data as { message: string }).message);
    }
  },
});

const handleLogin = async (payload: { token: string }) => {
  try {
    await login(payload);
    showSuccess('Logged in successfully');
  } catch (err) {
    showError(err instanceof Error ? err.message : 'Login failed');
  }
};

const handleNewModpack = () => {
  showForm.value = true;
  showSettings.value = false;
  selectedModpack.value = null;
};

const handleSelectModpack = (id: number) => {
  selectedModpack.value = id;
  showForm.value = false;
  showSettings.value = false;
};

const handleShowSettings = () => {
  showSettings.value = true;
  showForm.value = false;
  selectedModpack.value = null;
};

const handleModpackUpdate = (payload: { id: number; data: Partial<ModpackResponse> }) => {
  modpacks.value = modpacks.value.map((modpack) =>
    modpack.id === payload.id ? { ...modpack, ...payload.data } : modpack,
  );
};

const handleModpackDelete = async (id: number) => {
  try {
    await apiService.deleteModpack(id);
    modpacks.value = modpacks.value.filter((modpack) => modpack.id !== id);
    if (selectedModpack.value === id) {
      selectedModpack.value = null;
    }
  } catch (err) {
    console.error('Failed to delete modpack:', err);
    await loadModpacks();
  }
};

const handleFormSubmit = async (_: ModpackBase) => {
  await loadModpacks();
  showForm.value = false;
  showSettings.value = false;
};

const handleSettingsSave = (settings: SettingResponse[]) => {
  showSuccess('Settings saved successfully');
  showSettings.value = false;
};

const handleBuild = async () => {
  try {
    building.value = true;
    await apiService.buildModpacks();
    showSuccess('Build started successfully!');
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Build failed';
    showError(`Build failed: ${message}`);
  } finally {
    building.value = false;
  }
};
</script>

<template>
  <div>
    <NotificationToast :type="notification.type" :message="notification.message" :is-visible="notification.isVisible"
      @close="hideNotification" />

    <LoginForm v-if="!isAuthenticated" :loading="authLoading" :error="authError" @login="handleLogin" />

    <div v-else class="flex min-h-screen">
      <ModpackSidebar :modpacks="modpacks" :selected-modpack="selectedModpack" :show-form="showForm"
        :show-settings="showSettings" :building="building" @select="handleSelectModpack" @new="handleNewModpack"
        @show-settings="handleShowSettings" @logout="logout" @build="handleBuild" />

      <main class="flex-1 p-8">
        <div v-if="loading" class="min-h-[60vh] flex items-center justify-center">
          <div class="text-xl">Loading...</div>
        </div>

        <div v-else-if="error" class="min-h-[60vh] flex items-center justify-center">
          <div class="text-center">
            <div class="text-xl mb-4">
              Error: {{ error }}
            </div>
            <Button @click="loadModpacks">
              Retry
            </Button>
          </div>
        </div>

        <div v-else>
          <ModpackForm v-if="showForm" @submitted="handleFormSubmit" />
          <SettingsForm v-else-if="showSettings" @saved="handleSettingsSave" />
          <ModpackDetails v-else-if="selectedModpackData" :key="selectedModpackData.id" :modpack="selectedModpackData"
            @updated="handleModpackUpdate" @deleted="handleModpackDelete" />
          <div v-else class="flex items-center justify-center min-h-[60vh] p-4">
            <Card class="w-full max-w-xl">
              <CardHeader class="text-center">
                <CardTitle class="text-2xl">Welcome to Modpack Manager</CardTitle>
                <CardDescription>
                  Select a modpack from the sidebar or create a new one to get started.
                </CardDescription>
              </CardHeader>
              <CardContent class="text-center">
                <Button size="lg" @click="handleNewModpack">
                  Create New Modpack
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  </div>
</template>
